import { Platform, PlatformExtensions } from './types/GenericTypes';
import keyMirror from 'keymirror';

export const PLATFORMS: Platform = keyMirror({
	atari_2600: null,
	atari_7800: null,
	atari_jaguar: null,
	atari_lynx: null,
	colecovision: null,
	channel_f: null,
	intellivision: null,
	neo_geo_pocket_color: null,
	nintendo_3ds: null,
	nintendo_64: null,
	nintendo_ds: null,
	nes: null,
	nintendo_gameboy: null,
	nintendo_gameboy_advance: null,
	nintendo_gameboy_color: null,
	nintendo_gamecube: null,
	nintendo_virtual_boy: null,
	nintendo_wii: null,
	cdi: null,
	sega_32x: null,
	sega_cd: null,
	sega_dreamcast: null,
	sega_game_gear: null,
	sega_genesis: null,
	sega_master_system: null,
	sega_saturn: null,
	sony_playstation: null,
	sony_playstation2: null,
	sony_psp: null,
	snes: null,
	turbografx_16: null,
	watara_supervision: null
});

export const PLATFORM_FILE_EXTENSIONS: PlatformExtensions = {
	atari_2600: [],
	atari_7800: [],
	atari_jaguar: [],
	atari_lynx: [],
	colecovision: [],
	channel_f: [],
	intellivision: [],
	neo_geo_pocket_color: [],
	nintendo_3ds: [],
	nintendo_64: [],
	nintendo_ds: [],
	nes: [],
	nintendo_gameboy: [],
	nintendo_gameboy_advance: [],
	nintendo_gameboy_color: [],
	nintendo_gamecube: ['.iso', '.gcm'],
	nintendo_virtual_boy: [],
	nintendo_wii: ['.iso', '.wbfs'],
	cdi: [],
	sega_32x: [],
	sega_cd: [],
	sega_dreamcast: [],
	sega_game_gear: [],
	sega_genesis: [],
	sega_master_system: [],
	sega_saturn: [],
	sony_playstation: [],
	sony_playstation2: [],
	sony_psp: [],
	snes: [],
	turbografx_16: [],
	watara_supervision: []
};
